class SpritzKernel:
    def __init__(self) -> None: ...
    def absorb(self, buffer: bytes) -> None: ...
    def absorb_number(self, n: int) -> None: ...
    def absorb_stop(self) -> None: ...
    def drip_byte(self) -> int: ...
    def drip(self, buffer:bytearray) -> None: ...
    def reset(self) -> None: ...
    def skip(self, amt: int) -> None: ...
    def xor(self, buffer:bytearray) -> None: ...
