[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rwt-bascat"
version = "1.0"
description = "decodes tokenized GW-BASIC/BASICA files"
authors = [{ name = "Richard Todd" }]
requires-python = ">=3.13"
license = { text = "MIT" }
readme = "README.md"
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
]

[project.scripts]
bascat = "rwt_bascat._cli:main"

[project.urls]
Repository = "https://github.com/rwtodd/small_python_packages.git"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["rwt_bascat"]

[[tool.setuptools.ext-modules]]
name = "rwt_bascat._core"
sources = ["src/rwt_bascat/_core.c"]
py-limited-api = true