[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rwt-spritz"
version = "1.0"
description = "provides spritz cipher routines"
authors = [{ name = "Richard Todd" }]
requires-python = ">=3.13"
license = { text = "MIT" }
readme = "README.md"
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
]

[project.scripts]
spritz = "rwt_spritz._cli:main"

[project.urls]
Repository = "https://github.com/rwtodd/small_python_packages.git"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["rwt_spritz"]

[[tool.setuptools.ext-modules]]
name = "rwt_spritz._internal"
sources = ["src/rwt_spritz/_internal.c"]
py-limited-api = true