from typing import Any

WAVE_SQUARE: int
WAVE_TRIANGLE: int
WAVE_SAWTOOTH: int
WAVE_SINE: int
VARIANT_TANDY: int
VARIANT_SEGA: int
PIT_CLOCK_HZ: int

class PCSpeakerCore:
    def __init__(
        self, sample_rate: float = 44100.0, amplitude: float = 0.25
    ) -> None: ...
    @property
    def sample_rate(self) -> float: ...
    @property
    def frequency_hz(self) -> float: ...
    @property
    def gate(self) -> bool: ...
    @property
    def waveform(self) -> int: ...
    @property
    def amplitude(self) -> float: ...
    def reset(self) -> None: ...
    def set_frequency_hz(self, f: float) -> None: ...
    def set_pit_divisor(self, divisor: int) -> None: ...
    def set_gate(self, on: bool) -> None: ...
    def set_waveform(self, waveform: int) -> None: ...
    def set_amplitude(self, amplitude: float) -> None: ...
    def render_into(self, destination: Any) -> None: ...

class SN76496Core:
    def __init__(
        self,
        variant: int = 0,
        sample_rate: float = 44100.0,
        clock_hz: float = 0.0,
        master_gain: float = 0.25,
    ) -> None: ...
    @property
    def sample_rate(self) -> float: ...
    @property
    def clock_hz(self) -> float: ...
    @property
    def variant(self) -> int: ...
    def reset(self) -> None: ...
    def write(self, *args: int) -> None: ...
    def set_tone(
        self, channel: int, period: int = ..., volume: int = ...
    ) -> None: ...
    def set_noise(self, control: int = ..., volume: int = ...) -> None: ...
    def set_tone_waveform(self, channel: int, waveform: int) -> None: ...
    def tone_frequency(self, channel: int) -> float: ...
    def render_into(self, destination: Any) -> None: ...

NES_REGION_NTSC: int
NES_REGION_PAL: int
NES_NTSC_CPU_HZ: int
NES_PAL_CPU_HZ: int

class NesApuCore:
    def __init__(
        self,
        sample_rate: float = 44100.0,
        region: int = 0,
        cpu_clock_hz: float = 0.0,
        master_gain: float = 0.5,
    ) -> None: ...
    @property
    def sample_rate(self) -> float: ...
    @property
    def cpu_clock_hz(self) -> float: ...
    @property
    def region(self) -> int: ...
    def reset(self) -> None: ...
    def clock(self, cpu_cycles: int) -> int: ...
    def write(self, addr: int, value: int) -> None: ...
    def read(self, addr: int) -> int: ...
    def samples_available(self) -> int: ...
    def irq_pending(self) -> bool: ...
    def set_dmc_reader(self, reader: Any) -> None: ...
    def drain_into(self, destination: Any) -> None: ...
    def render_into(self, destination: Any) -> None: ...
